version: "3"
services:
  #Laravel App
  #  The Application
  app:
    container_name: laravel_app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "DB_DATABASE=birdboard"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
      - "APP_DEBUG=true"
      - "APP_KEY=base64:diZBCGA5WjBCHzfp4BYFt0vNOACOduFt8MuspwuajUM="
    ports:
      - 9000:80

  #MySQL Service
  # The Database
  database:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=birdboard"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 8991:3306

volumes:
  dbdata:

